version: "2"
services:
  devenv:
    image: ubuntu:16.04
    command: ['/usr/bin/dumb-init', '/bin/bash']

registries: {}
  # Add optional registries used for deployment. For example:
  #  google:
  #    url: https://gcr.io
  #    namespace: my-cool-project-xxxxxx
